# Generated by Django 3.0.6 on 2020-06-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='perfil/avatar.png', max_length=200, upload_to='perfil/', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
