# Generated by Django 3.0.6 on 2020-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0002_auto_20200629_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
