# Generated by Django 3.0.6 on 2020-06-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0002_auto_20200519_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'ordering': ['id_autor']},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['id_categoria']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id_cliente']},
        ),
        migrations.AlterModelOptions(
            name='libros',
            options={'ordering': ['isbn']},
        ),
        migrations.AlterModelOptions(
            name='pedidoscliente',
            options={'ordering': ['nro_pedido']},
        ),
        migrations.DeleteModel(
            name='LibroPorAutor',
        ),
    ]
