# Generated by Django 3.0.6 on 2020-06-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0002_auto_20200609_0927'),
        ('libreriaApp', '0002_auto_20200519_1107'),
    ]

    operations = [
    ]
