# Generated by Django 3.0.6 on 2020-06-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libreriaApp', '0003_merge_20200629_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autores',
            options={'ordering': ['id_autor']},
        ),
        migrations.AlterField(
            model_name='pedidoscliente',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoscliente',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
