# Generated by Django 3.0.6 on 2020-06-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0003_auto_20200607_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='id_categorias',
            new_name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='pedidoscliente',
            name='id',
        ),
        migrations.AddField(
            model_name='libros',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros',
            name='id_autor',
            field=models.ManyToManyField(to='libreriaApp.Autores'),
        ),
        migrations.AddField(
            model_name='pedidoscliente',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoscliente',
            name='id_pedido',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoscliente',
            name='isbn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreriaApp.Libros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libros',
            name='fecha_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libros',
            name='portada',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='portada/', verbose_name='Imagen de Portada'),
        ),
        migrations.AlterField(
            model_name='pedidoscliente',
            name='fecha_pedido',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidoscliente',
            name='nro_pedido',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='autores',
            table=None,
        ),
        migrations.AlterModelTable(
            name='categorias',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='libros',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pedidoscliente',
            table=None,
        ),
    ]
